name: github pages

on:
  workflow_dispatch:
    branches: [ 'main' ]
  push:
    branches: [ 'main' ]

concurrency: publish_pages_lock

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      # needs to git diff the repo
      contents: write
      # write artifacts and comment on pr related to this
      pull-requests: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod
      - name: "Setup Hugo"
        id: pages
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      #          hugo-version: '0.91.2'
      - name: "NPM build"
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: "Hugo Build"
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo && hugo --minify
      #        run: hugo && hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          cname: "code-space.dev"
          github_token: ${{ secrets.CI_TOKEN_WORKFLOW }}
          publish_dir: ./public
