name: github pages

on:
  workflow_dispatch:
    branches: [ 'main' ]
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      # needs to git diff the repo
      contents: write
      # write artifacts and comment on pr related to this
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: "Build"
        run: |
          ls -lah || true
          ls -lah themes || true
          ls -lah themes/LoveIt || true
          hugo version || true
          hugo --minify
      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.DUCK_GITHUB_TOKEN }}
          publish_dir: ./public
